# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1127, 861)
        Form.setAcceptDrops(False)
        self.video_input = QtWidgets.QPushButton(Form)
        self.video_input.setGeometry(QtCore.QRect(230, 40, 121, 31))
        self.video_input.setObjectName("video_input")
        self.det = QtWidgets.QPushButton(Form)
        self.det.setGeometry(QtCore.QRect(490, 660, 141, 51))
        self.det.setObjectName("det")
        self.camera = QtWidgets.QRadioButton(Form)
        self.camera.setGeometry(QtCore.QRect(870, 40, 171, 41))
        self.camera.setAutoFillBackground(True)
        self.camera.setObjectName("camera")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(390, 40, 361, 31))
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.frame_label = QtWidgets.QLabel(Form)
        self.frame_label.setGeometry(QtCore.QRect(120, 100, 951, 541))
        self.frame_label.setAutoFillBackground(True)
        self.frame_label.setText("")
        self.frame_label.setObjectName("frame_label")
        self.video_input.raise_()
        self.camera.raise_()
        self.label.raise_()
        self.frame_label.raise_()
        self.det.raise_()

        self.retranslateUi(Form)
        self.video_input.clicked.connect(Form.push_vid)
        self.det.clicked.connect(Form.begin_det)
        self.camera.clicked.connect(Form.from_camera)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.video_input.setText(_translate("Form", "视频文件输入"))
        self.det.setText(_translate("Form", "开始检测"))
        self.camera.setText(_translate("Form", "摄像头输入"))
        self.label.setText(_translate("Form", "空"))
